tasks:
  - name: start the containers
    init: ./setup.sh
    command: docker-compose up -d --build
  - name: wait for containers
    # this is so hashtag delicious
    init: until (( $(docker ps -q | wc -l) == 3 )); do sleep 1; clear; echo "Waiting for the containers to start up...when they're ready, the browser window will open above..."; done
    command: echo "let's start the recon!"
    openMode: tab-after
  - name: delete the evidence
    # no idea if this is long enough to start up the docker-compose, but let's find out!
    command: sleep 5 && rm docker-compose.yml Dockerfile-* *.sh && exit
