tasks:
  - name: start the containers
    init: ./setup.sh
    command: docker-compose up -d --build && exit
  - name: wait for containers
    # this is so hashtag delicious
    init: until (( $(docker ps -q | wc -l) == 3 )); do sleep 1; clear; echo "Waiting for the containers to start up...when they're ready, you'll be ssh'ed into the first container..."; done
    command: ssh -i initial-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null alice@$(docker inspect $(docker ps | grep first | awk '{print $1}') | jq -r '.. | ."IPAddress"? | select(. != null and . != "")')
    openMode: tab-after
  - name: delete the evidence
    # no idea if this is long enough to start up the docker-compose, but let's find out!
    command: sleep 5 && rm docker-compose.yml Dockerfile-* *.sh && exit
