FROM ubuntu:latest

# Install SSH and nmap
RUN apt-get update && apt-get install -y \
  openssh-client \
  nmap \
  net-tools \
  netcat

# Create a directory to store the SSH keys in the container
RUN useradd -m alice -s /bin/bash && mkdir /home/alice/.ssh

# Copy the SSH keys into the container
COPY ./generated-keys/key-1 /home/alice/.ssh/
COPY ./generated-keys/key-2 /home/alice/.ssh/
COPY ./generated-keys/key-3 /home/alice/.ssh/

# Set the appropriate permissions for the SSH folder and keys
RUN chmod 700 /home/alice/.ssh
RUN chmod 600 /home/alice/.ssh/key*
RUN chown -R alice:alice /home/alice/.ssh

# Let the user run nmap without sudo
RUN chown alice:alice $(which nmap)

USER alice

WORKDIR /home/alice

RUN echo "mario\nluigi\nwario" >> users.txt

# Set the default command for the container
CMD ["/bin/bash", "-c", "sleep 3600"]
