FROM ubuntu:22.04

RUN apt update -y && apt install -y \
  openssh-server

# Configure SSH
RUN mkdir /var/run/sshd

RUN useradd -m bigbird -s /bin/bash && mkdir /home/bigbird/.ssh

COPY ./more-generated-keys/key-3.pub /home/bigbird/.ssh/authorized_keys

RUN chown bigbird:bigbird /home/bigbird/.ssh/authorized_keys && \
  chown bigbird:bigbird /home/bigbird/.ssh && \
  chmod 700 /home/bigbird/.ssh && \
  chmod 600 /home/bigbird/.ssh/authorized_keys

RUN echo "FOUND ME" >> /home/bigbird/flag.txt

USER bigbird

RUN ssh-keygen -A

USER root

RUN sed -i 's/#Port 22/Port 9001/' /etc/ssh/sshd_config

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]
