FROM ubuntu:22.04

RUN apt update && apt install -y --no-install-recommends \
  openssh-server

RUN apt install -y --no-install-recommends \
  netcat \
  net-tools \
  nmap

# Configure SSH
RUN mkdir /var/run/sshd

RUN useradd -m moana -s /bin/bash && mkdir /home/moana/.ssh

# Copy the SSH keys into the container
COPY ./more-generated-keys/key-* /home/moana/.ssh/

COPY ./generated-keys/key-2.pub /home/moana/.ssh/authorized_keys

RUN chown moana:moana -R /home/moana/.ssh && \
  chmod 700 /home/moana/.ssh && \
  chmod 600 /home/moana/.ssh/authorized_keys

RUN echo "bert\nbigbird\ncookiemonster" >> /home/moana/users.txt
RUN echo "meWantCookie\n3rn13\nSnuffie" >> /home/moana/passwords.txt

USER moana

RUN ssh-keygen -A

USER root

# This port number will be overwritten during setup to a random value
RUN sed -i 's/#Port 22/Port FIRST_PORT/' /etc/ssh/sshd_config

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]
