FROM ubuntu:22.04

RUN apt update && apt install -y \
  openssh-server \
  netcat \
  net-tools \
  nmap

# Configure SSH
RUN mkdir /var/run/sshd

# Create a directory to store the SSH keys in the container
RUN useradd -m alice -s /bin/bash && mkdir /home/alice/.ssh

# Copy the SSH keys into the container
COPY ./generated-keys/key-1 /home/alice/.ssh/
COPY ./generated-keys/key-2 /home/alice/.ssh/
COPY ./generated-keys/key-3 /home/alice/.ssh/

# Copy in the initial key
COPY ./initial-key.pub /home/alice/.ssh/authorized_keys

# Set the appropriate permissions for the SSH folder and keys
RUN chmod 700 /home/alice/.ssh
RUN chmod 600 /home/alice/.ssh/key*
RUN chown -R alice:alice /home/alice/.ssh

# Let the user run nmap without sudo
RUN chown alice:alice /usr/bin/nmap

USER alice

RUN ssh-keygen -A

USER root

RUN echo "ariel\njasmine\nmoana" >> /home/alice/users.txt

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]