FROM ubuntu:22.04

RUN apt update -y && apt install -y openssh-server netcat net-tools nmap

# Configure SSH
RUN mkdir /var/run/sshd
RUN echo 'root:initial' | chpasswd

RUN useradd -d /home/alice -p password alice \
  && useradd -d /home/bob -p password bob \
  && useradd -d /home/patrick -p password patrick

#password for user login
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]
