FROM ubuntu:22.04

RUN apt update && apt install -y --no-install-recommends \
  openssh-server

# Configure SSH
RUN mkdir /var/run/sshd

RUN useradd -m bigbird -s /bin/bash && mkdir /home/bigbird/.ssh

COPY ./more-generated-keys/key-3.pub /home/bigbird/.ssh/authorized_keys

RUN chown bigbird:bigbird -R /home/bigbird/.ssh && \
  chmod 700 /home/bigbird/.ssh && \
  chmod 600 /home/bigbird/.ssh/authorized_keys

RUN echo "FOUND ME" >> /home/bigbird/flag.txt

USER bigbird

RUN ssh-keygen -A

USER root

# This port number will be overwritten during setup to a random value
RUN sed -i 's/#Port 22/Port SECOND_PORT/' /etc/ssh/sshd_config

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]
